x-bwrap-security: &bwrap-security
  cap_add:
    - SYS_ADMIN
  security_opt:
    - apparmor=unconfined
    - seccomp=unconfined

services:
  mira-gateway:
    <<: *bwrap-security

  mira-api:
    <<: *bwrap-security

  mira-cli:
    <<: *bwrap-security
